background_opacity 0.70
enable_gpu no

font_size 11.0
font_family monospace

selection_foreground #ffffff
selection_background #399680

cursor #ffffff
cursor_trail 1
cursor_trail_color #399680

enable_audio_bell yes

editor nano
color2  #399680
